const ARTICLES = [
  {
    id: "start-before-ready",
    topic: "mindset",
    title: "Start Before You're Ready",
    excerpt: "Waiting for the perfect moment is the oldest trap in the book. The conditions will never be ideal. Your only move is to begin.",
    date: "April 18, 2026",
    readTime: "5 min read",
    featured: true,
    body: `
      <p>There's a lie most people tell themselves every single day: <em>"I'll start when I'm ready."</em> Ready for what, exactly? Ready for all the fear to disappear? Ready for someone to hand you a guarantee? That moment doesn't come.</p>

      <h2>The Readiness Myth</h2>
      <p>We've been conditioned to believe readiness is a state we arrive at — like a green light that switches on when you've done enough research, saved enough money, or built enough confidence. But readiness is not a destination. It's a feeling that follows action, not one that precedes it.</p>
      <p>Every person you admire who built something meaningful started before they felt ready. They launched the business with an imperfect product. They posted the article before they felt like a writer. They had the hard conversation before they had the right words.</p>

      <blockquote>The secret is not to wait for the fear to leave — it's to move with it still in the room.</blockquote>

      <h2>What "Not Ready" Really Means</h2>
      <p>When you say you're not ready, you're usually saying one of three things:</p>
      <ul>
        <li>You're afraid of failing publicly</li>
        <li>You don't believe you deserve success yet</li>
        <li>You're comfortable where you are</li>
      </ul>
      <p>All three are valid feelings. None of them are valid reasons to stay still.</p>

      <h2>The First Step Is the Whole Game</h2>
      <p>Momentum is generated by movement, not by thought. Once you take the first step — no matter how imperfect — your brain shifts from "what if" to "what's next." That shift is everything.</p>
      <p>Don't wait for the green light. Build the light yourself. Start today, with what you have, from where you are. Adjust as you go. That's the only process that's ever worked.</p>
    `
  },
  {
    id: "discipline-over-motivation",
    topic: "discipline",
    title: "Discipline Beats Motivation Every Time",
    excerpt: "Motivation is a mood. Discipline is a system. One fades when things get hard — the other is built for exactly that moment.",
    date: "April 10, 2026",
    readTime: "6 min read",
    featured: true,
    body: `
      <p>Motivation feels incredible when it shows up. It makes you want to run ten miles, overhaul your diet, and build an empire — all before noon. The problem is that motivation is a visitor, not a resident. It comes and goes without warning.</p>

      <h2>The Motivation Trap</h2>
      <p>When people rely on motivation, they work in bursts. Three days of intense effort, then a week of nothing. They're always waiting for the feeling to return before they can act again. This is not a strategy. This is a cycle.</p>
      <p>The highest performers in any field are not more motivated than you. They've simply built systems that don't require motivation to function.</p>

      <blockquote>You don't rise to the level of your goals. You fall to the level of your systems.</blockquote>

      <h2>What Discipline Actually Is</h2>
      <p>Discipline is the commitment to act regardless of how you feel in the moment. It's showing up to the gym when you're tired. Writing when you're uninspired. Doing the work when the work is boring.</p>
      <p>Discipline is built, not found. You don't discover it — you develop it through repeated small acts of doing what you said you'd do, especially when every part of you doesn't want to.</p>

      <h2>Building Your System</h2>
      <p>Start small. Choose one habit. Attach it to something you already do. Protect it. Do it for thirty days. Watch what happens to your sense of self-trust. Then stack another habit on top.</p>
      <p>Discipline compounds. Every day you show up when you don't feel like it, you become someone who shows up. That identity is worth more than any single result.</p>
    `
  },
  {
    id: "the-cost-of-comfort",
    topic: "resilience",
    title: "The Hidden Cost of Staying Comfortable",
    excerpt: "Comfort feels safe but it has a price: the slow erosion of who you could have been. The most dangerous place to live is inside your comfort zone.",
    date: "April 3, 2026",
    readTime: "4 min read",
    featured: true,
    body: `
      <p>Nobody talks about the cost of comfort. We talk constantly about the risk of chasing your goals, the possibility of failure, the danger of the unknown. But we almost never talk about the price you pay for staying exactly where you are.</p>

      <h2>Comfort Is a Slow Leak</h2>
      <p>Staying comfortable doesn't feel like a choice — it feels like the absence of a choice. Like you're just waiting for the right moment. But every day you choose comfort over growth, you're making a trade: potential for safety.</p>
      <p>That trade feels fine today. And tomorrow. But years later, people look back and realize the greatest regret isn't the things they tried and failed at — it's the things they never tried at all.</p>

      <blockquote>The most uncomfortable truth: your comfort zone is not protecting you. It's containing you.</blockquote>

      <h2>Growth Requires Discomfort</h2>
      <p>Every skill you have right now was once outside your comfort zone. You didn't know how to walk, talk, read, or drive — until you pushed through the discomfort of learning. Growth has always worked this way. The discomfort is not a sign something is wrong. It's a sign something is changing.</p>

      <h2>One Step Outside</h2>
      <p>You don't have to burn everything down. Just take one step outside your comfort zone this week. One hard conversation. One new skill attempted. One risk taken. The zone expands every time you push its edges. And over time, what once felt terrifying becomes your new normal.</p>
    `
  },
  {
    id: "goal-setting-that-works",
    topic: "goals",
    title: "Goal Setting That Actually Works",
    excerpt: "Most goals fail not because people lack ambition but because they lack a clear, actionable structure. Here's how to set goals you'll actually hit.",
    date: "March 28, 2026",
    readTime: "7 min read",
    featured: false,
    body: `
      <p>Setting goals is the easy part. Everyone has dreams, ambitions, things they'd love to achieve. The hard part is building the bridge between where you are and where you want to be — and most people never figure that out.</p>

      <h2>The Problem with Vague Goals</h2>
      <p>"I want to get fit." "I want to make more money." "I want to be happier." These are wishes, not goals. Goals have specificity, timelines, and measurable outcomes. Without those elements, a goal is just a hope dressed up as intention.</p>

      <h2>The Structure That Works</h2>
      <p>For any meaningful goal, you need three things:</p>
      <ol>
        <li><strong>A clear outcome:</strong> What does success look like, exactly?</li>
        <li><strong>A deadline:</strong> When will you know if you've achieved it?</li>
        <li><strong>Daily actions:</strong> What do you do today, this week, this month?</li>
      </ol>
      <p>Most people spend all their energy on the outcome and none on the daily actions. That's backwards. The outcome is the target; the daily actions are the shots.</p>

      <blockquote>A goal without a plan is just a wish. A plan without daily action is just a fantasy.</blockquote>

      <h2>Review and Adjust</h2>
      <p>Goals aren't set-and-forget. Build a weekly review habit. Ask: What did I do? What worked? What didn't? What do I adjust? This 15-minute practice will do more for your progress than any goal-setting framework.</p>
    `
  },
  {
    id: "morning-habits-of-winners",
    topic: "habits",
    title: "The Morning Habits That Change Everything",
    excerpt: "How you start your morning sets the tone for everything that follows. These five habits will transform your days — and your life.",
    date: "March 21, 2026",
    readTime: "5 min read",
    featured: false,
    body: `
      <p>Your morning is the most powerful part of your day. Before the world starts making demands on your time, energy, and attention, you have a window — usually 60 to 90 minutes — that is entirely yours. What you do with it determines everything.</p>

      <h2>1. Don't Touch Your Phone</h2>
      <p>The first thing most people do is reach for their phone. This instantly puts you in reactive mode — responding to others' priorities instead of your own. Give yourself at least 30 minutes before checking anything.</p>

      <h2>2. Move Your Body</h2>
      <p>Exercise first thing triggers a cascade of benefits: elevated mood, sharper focus, more energy. Even 20 minutes of movement changes the chemical makeup of your day.</p>

      <h2>3. Set Your One Priority</h2>
      <p>Before your day starts, identify the single most important thing you need to accomplish. Not a list — one thing. Everything else is secondary.</p>

      <h2>4. Read or Learn Something</h2>
      <p>Feed your mind something useful in the morning. A chapter of a book, an article, a podcast. You're planting seeds that shape your thinking for the rest of the day.</p>

      <blockquote>Win the morning, win the day. It's that simple — and that hard.</blockquote>

      <h2>5. Protect the Habit</h2>
      <p>The most important morning habit is to have one at all. Whatever your routine is, protect it. Wake up at the same time. Guard those first hours. Over time, a strong morning routine becomes your anchor — the foundation everything else is built on.</p>
    `
  },
  {
    id: "failure-is-data",
    topic: "mindset",
    title: "Failure Is Not the Opposite of Success",
    excerpt: "Every setback contains information. The people who win long-term are the ones who treat failure as feedback, not as a verdict.",
    date: "March 14, 2026",
    readTime: "5 min read",
    featured: false,
    body: `
      <p>We've built an entire cultural story around failure — that it's shameful, final, proof that you're not good enough. That story is not only wrong, it's actively harmful. It keeps people from trying, and keeps those who do try from learning what they need to learn.</p>

      <h2>Reframe the Word</h2>
      <p>Failure is data. It tells you what didn't work, under what conditions, and why. That information is invaluable — more valuable, often, than any success. Successes confirm what you're doing right. Failures reveal what you need to change.</p>

      <blockquote>You don't fail your way out of a goal. You fail your way toward it — if you're paying attention.</blockquote>

      <h2>The Question That Changes Everything</h2>
      <p>Instead of asking "Why did this happen to me?" ask "What did this teach me?" The first question keeps you stuck. The second one moves you forward.</p>

      <h2>The Long Game</h2>
      <p>Every highly successful person has a long list of failures. They're not successful despite those failures — in many cases, they're successful because of them. The failures built the skills, the resilience, and the wisdom that made success possible.</p>
      <p>Your failures are not the end of your story. They're the chapters that make the ending worth reading.</p>
    `
  },
  {
    id: "building-real-confidence",
    topic: "success",
    title: "How to Build Real, Unshakeable Confidence",
    excerpt: "Real confidence isn't something you're born with. It's something you build — through action, proof, and a relationship with discomfort.",
    date: "March 7, 2026",
    readTime: "6 min read",
    featured: false,
    body: `
      <p>Most people think confidence is a trait — something you either have or you don't. But real confidence, the kind that doesn't crumble under pressure, is something built systematically over time. And the blueprint is simpler than you think.</p>

      <h2>Confidence Comes from Evidence</h2>
      <p>The reason most people lack confidence is that they haven't given themselves enough evidence that they're capable. They set big goals, don't achieve them, and conclude they're not good enough. The fix is to start smaller, win consistently, and use those wins as proof.</p>

      <h2>Do Hard Things on Purpose</h2>
      <p>Every time you do something difficult — something that scared you, something you weren't sure you could do — and you survive it, your brain updates its model of what you're capable of. This is the engine of real confidence.</p>

      <blockquote>Confidence is built in the doing, not the thinking.</blockquote>

      <h2>Stop Waiting to Feel Ready</h2>
      <p>Confident people act before they feel confident. That's not bravado — it's strategy. They've learned that the feeling follows the action, not the other way around. You become confident by doing the thing, not by deciding you're ready to do the thing.</p>

      <h2>The Compounding Effect</h2>
      <p>Small wins compound into big confidence. Every kept promise to yourself. Every hard workout completed. Every difficult conversation had. They stack. After a year of this, you barely recognize the person you used to be.</p>
    `
  },
  {
    id: "the-one-percent-rule",
    topic: "habits",
    title: "The 1% Rule: Small Gains, Massive Results",
    excerpt: "Improving by just 1% every day sounds trivial. After a year, you'll be 37 times better. Tiny habits, compounded over time, are the real secret.",
    date: "February 28, 2026",
    readTime: "4 min read",
    featured: false,
    body: `
      <p>People overestimate what they can do in a day and dramatically underestimate what they can do in a year. The 1% rule exists at the intersection of those two truths.</p>

      <h2>The Math of Marginal Gains</h2>
      <p>If you improve by just 1% every day, the compound effect over a year is staggering: 1.01^365 = 37.78. You become 37 times better. Conversely, if you decline by 1% each day: 0.99^365 = 0.03. You effectively become nothing.</p>
      <p>The difference between these two trajectories is tiny each day. Over a year, it's everything.</p>

      <blockquote>You don't need massive change. You need consistent, directional movement. The rest is math.</blockquote>

      <h2>How to Apply It</h2>
      <p>Pick one area of your life. Identify the smallest possible improvement you could make to your process today. Implement it. Tomorrow, do it again. This is not glamorous. But it works with a precision that willpower and motivation never can.</p>

      <h2>The Identity Shift</h2>
      <p>After enough days of 1% improvement, something remarkable happens: you stop being someone who is trying to improve and start being someone who improves. The habit becomes who you are. And that identity is the most durable foundation you can build.</p>
    `
  }
];

const DAILY_QUOTES = [
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
];
